In [34]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [35]:
df = pd.read_csv('C:\\users\\mirid\\houseprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [40]:
median = df.bedrooms.median()
median

4.0

In [43]:
df.bedrooms = df.bedrooms.fillna(median)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [44]:
reg = linear_model.LinearRegression()


In [45]:
reg.fit(df[['area','bedrooms','age']],df.price)


LinearRegression()

In [47]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [48]:
reg.intercept_

221323.00186540408

In [49]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [50]:
reg.predict([[2500,4,5]])

array([578876.03748933])